version: "3"
services:
  db:
    image: mysql:5.6
    environment:
      # MYSQL_DATABASE: B_products_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      # MYSQL_PASSWORD: password
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        # データの永続化
    ports:
      - "4306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/workdir
